### PR TITLE
added escape sequences to git prompt also

### PR DESCRIPTION
**Pull request by bcismariu**
this is also regarding #403 

when the prompt was not sent to a separate line the bug would still appear.
these changes fix this behaviour

### CODE REVIEW

**Comment by mathiasbynens** [comment]
@bcismariu Thanks!

> when the prompt was not sent to a separate line the bug would still appear.

Do you have a simple test case I can use to confirm the fix?

**Comment by bcismariu** [comment]
on your current .bash_prompt file comment line 115: PS1+="\n"; (this would keep the prompt on the same line)
now #403 will reappear. be properly escaping colors we now fix this issue.

**Comment by mathiasbynens** [comment]
@bcismariu I meant, can you provide a command that causes the issue using the old prompt?

**Comment by bcismariu** [comment]
this is the original file (all seems ok)
image

this is what happens when i keep the prompt on the same line (only commenting line 115 in the original file)
image

this is how it looks like after the fix:
image

**Comment by mathiasbynens** [comment]
Aaah, that’s what I was missing. Thanks for your patience, @bcismariu! Merging now.

**Comment by leonklingele** [comment]
Does this supersede #537?

**Pull request closed without merging**
