### PR TITLE
LS_COLORS -> LSCOLORS

### PR DESCRIPTION
**Pull request by asafch**
Hey,

the environment variable `LS_COLORS` defined in `.aliases` doesn't work in `Terminal.app`.
The definition used is compatible with Linux, not with OS X. Also, in OS X the variable's name should be `LSCOLORS` (without the underscore).
Please refer to my version of my file (line 33, latest commit af9ab14) to see a working definition for this variable.

### CODE REVIEW

**Comment by Tatsh** [comment]
`LS_COLORS` is for GNU `ls` and `LSCOLORS` is for BSD `ls`. This repository assumes you have Bash 4 as your shell.

**Comment by asafch** [comment]
Is there a reason to use GNU ls over BSD?

**Comment by asafch** [comment]
If so, then there's no point in detecting what's the color flag is in `.aliases` - it should always be `--color`.

**Comment by jeffbyrnes** [comment]
@asafch lots of other changes seem to have made it into this PR; I’d suggest it stands a better chance of being accepted if it does only what it says on the tin: properly utilize `LS_COLORS` and `LSCOLORS`, depending on flavor (GNU vs. BSD).

**Comment by asafch** [comment]
Good comment. I'll close this PR and open a new, specific one for this issue.

**Pull request closed without merging**
