### PR TITLE
github: Enable bash highlighting on github

### PR DESCRIPTION
**Pull request by fritx**
need `#!/usr/bin/env bash`
see also https://github.com/fritx/dotfiles/commit/f4270f73b62369e54c1e27fd79afe8614fc72be1

after:

before:

### CODE REVIEW

**Comment by fritx** [comment]
If i am missing something, let me know ;)

**Comment by mathiasbynens** [comment]
Thanks!

**Comment by fritx** [comment]
@mathiasbynens oops, thanks! I saw just a 'closed' on mobile, which made me confused.

**Comment by Tatsh** [comment]
Rather than have shebangs that really serve no purpose here, why not use `.gitattributes`?

https://github.com/github/linguist#using-gitattributes

**Comment by travi** [comment]
from that link:
> .gitattributes will be used to determine language statistics, but will not be used to syntax highlight files.

**Comment by Tatsh** [comment]
Right. :disappointed:

**Comment by travi** [comment]
plus, i do think it's a little harsh to say that the shebangs serve no purpose, since its good practice to include a shebang in _any_ script file

**Comment by Tatsh** [comment]
That is subjective. The shebang makes sense when the script is executable and if you run the script with direct invocation: `./script-name` (which is not possible without executable permissions; some hardened systems may disallow direct invocation except for the root user). Otherwise it is a comment and perhaps, in a machine-code (intended for machine reading and not the programmer) way, tells the programmer what interpreter to use (or is/was used). It does not necessarily say what language the script is written in. Only a comment intended for human consumption makes sense for this purpose IMHO. Unfortunately, GitHub has no other ways to detect languages except for shebangs and extensions.

**Comment by fritx** [comment]
@Tatsh @travi yeah, that also makes sense at my Sublime Text :joy:
So I guess it is kind of good practice?

**Comment by Tatsh** [comment]
For files with non-standard extension or no extension:
- Vim: use modeline
- Kate: use modeline or set language (which is stored in preferences in recent files for a set amount of time)
- GitHub: use shebang on (this is really flawed by comparison)

I thought `linguist-language` would do it, which would be far better as you do not have to modify your code just for GitHub display. Right now it does not.

**Pull request closed without merging**
