### PR TITLE
.macos: Speed up opening of folders upon drag and drop

### PR DESCRIPTION
**Pull request by mixn**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
This seems like a nice setting, but on checking, isn't this already part of the setup here? https://github.com/mathiasbynens/dotfiles/blob/b22c32290e1518c0f228afba254ee6a3f6ab6d7a/.macos#L267-L271

**Comment by mathiasbynens** [comment]
Closing as it’s already in there 😅 Thanks anyway!

**Comment by mixn** [comment]
@mathiasbynens Sorry I forgot to close when we texted about this… ALMOST FOUR MONTHS AGO. 🤦‍♂️

**Comment by mathiasbynens** [comment]
Classic @mixn.

**Pull request closed without merging**
