### PR TITLE
functions: unzip zip files into directory named after file without extension

### PR DESCRIPTION
**Pull request by tanertopal**
Adds a function to unzip zip files in subdirectory named after the zip filename without file extension.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@tanertopal AFAIK, that’s the default behavior of `unzip`.

**Comment by mathiasbynens** [comment]
Thanks for the suggestion! I wouldn’t be using this personally, so I’ll close this.

**Comment by tanertopal** [comment]
Ok 👍 @mathiasbynens 

@jeffbyrnes not sure it is. In my ```UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler``` it is definitely not the default behavior. It will just unpack everything into the current directory.

**Comment by jeffbyrnes** [comment]
@tanertopal well how about that. Alright!

**Pull request closed without merging**
