### PR TITLE
Add defaults command to disable Photos show up when devices are plugged

### PR DESCRIPTION
**Pull request by guerrero**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot I believe this will be of interest to you.

**Comment by Tatsh** [comment]
It says *(OS X 10.11 and earlier)*. Don't you mean Yosemite and up? Technically 10.10.3 and up.

**Comment by guerrero** [comment]
Maybe this command works in Yosemite but I've only tested it on El Capitan and, therefore, I can't ensure that it also works in earlier versions (10.10.3). If you've tried it and it works or you know anyone who has done it I will be happy to update that comment :)

**Comment by mathiasbynens** [comment]
@guerrero So you mean `(and later)` instead of `(and earlier)`?

**Comment by guerrero** [comment]
@mathiasbynens yep sorry, I was wrong

**Comment by mathiasbynens** [comment]
Have you tested whether `defaults write com.apple.ImageCapture disableHotPlug -bool true` works? (I don’t use `-currentHost` anywhere else in `.osx`, and would rather not start now.) It **should** work.

**Comment by guerrero** [comment]
Yep, I've tried to use it without the `-currentHost` flag and it doesn't work.

**Pull request closed without merging**
