### PR TITLE
Update .osx AppleHighlightColor to default

### PR DESCRIPTION
**Pull request by image72**
add recovery original value.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks, but `defaults delete NSGlobalDomain AppleHighlightColor` will do, like most other settings in `.osx`. I don’t think we should add the default value here.

**Comment by image72** [comment]
thanks a lot. 

in file .osx Line:28
make 

**volume control** radius border  not transparent.
 **contextmenu**
Image of contextmenu

=========
roductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B25

**Comment by guerrero** [comment]
@image72, that bug appears when you disable transparency. It's not a `defaults` bug, it's a bug in Yosemite. If you want to remove it disable `Preferences Panel > Accesibility > Reduce transparency` or use `defaults delete com.apple.universalaccess reduceTransparency` in your `Terminal.app`. BTW I prefer to see ugly radius and context menus than transparencies everywhere and I guess Mathias also think so.

**Comment by jonatack** [comment]
With the new beta build of OS X 10.10.2 (14C94b) of 3 days ago this seems to be fixed.

**Pull request closed without merging**
