### PR TITLE
vim: indentation improvement, pastetoggle, LF as EOL

### PR DESCRIPTION
**Pull request by heitorPB**
I like to have autoindent and smartindent in my vimrc.
Also, filetype indent on is nice.

### CODE REVIEW

**Comment by getsadzeg** [comment]
Is indentation related to colorscheme? Why did you change it to "delek"?

**Comment by heitorPB** [comment]
Indentation is not related to colorscheme. Just noticed I added a few personal changes to the PR also.  I prefer delek over solarized.

**Comment by getsadzeg** [comment]
So I think you should change title of PR, or remove your personal changes.

**Comment by mathiasbynens** [comment]
This patch changes some settings that I’d rather preserve.

**Pull request closed without merging**
