### PR TITLE
.osx: Suppress non-zero exit code when running `launchctl unload` twice

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details.

### CODE REVIEW

**Comment by Tatsh** [comment]
The script is not set to run with option `errexit` (`set -o errexit` to quit when there is a non-zero exit status on a command). Why would this be necessary?

**Comment by lucafavatella** [comment]
> The script is not set to run with option errexit (set -o errexit to quit when there is a non-zero exit status on a command). Why would this be necessary?

I do run my fork of the script with `set -e`, I spotted this, I fixed it locally and opened pull request in order to contribute back upstream and minimise diversion.

It is not necessary but I think clarifies the intention of the developer. And if you enable errexit (that I suggest) this will come back as useful.

Feel free to close without merging if not deemed appropriate for upstream.

**Comment by Tatsh** [comment]
What is the exact error that displays when `launchctl unload` is run twice (or more)?

**Comment by lucafavatella** [comment]
@Tatsh I get no error - neither on stdout nor stderr. I get exit code 1. Same result after reboot of the laptop, both first and second invocation after reboot. (I have not tested formatting the laptop and running the command again.)
```
$ launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
$ echo $?
1
$ ls -l /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
-rw-r--r--  1 root  wheel  1031 20 Feb  2015 /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
$ uname -rsv
Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27
$ sw_vers -productVersion
10.10.5
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.5 (14F27)
      Kernel Version: Darwin 14.5.0
      Boot Volume: [...]
      Boot Mode: Normal
      Computer Name: [...]
      User Name: [...]
      Secure Virtual Memory: [...]
      Time since boot: 11 minutes

```

I hope to be able to test on a laptop with an older version of OSX.

**Comment by lucafavatella** [comment]
> I hope to be able to test on a laptop with an older version of OSX.

```
$ launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
Could not open job overrides database at: /private/var/db/launchd.db/com.apple.launchd/overrides.plist: 13: Permission denied
launchctl: CFURLWriteDataAndPropertiesToResource(/System/Library/LaunchAgents/com.apple.notificationcenterui.plist) failed: -10
launchctl: Error unloading: com.apple.notificationcenterui.agent
$ echo $?
0
$ sudo launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
Password:
launchctl: Error unloading: com.apple.notificationcenterui.agent
$ echo $?
0
$ ls -l /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
-rw-r--r--  1 root  wheel  737 31 Oct  2013 /System/Library/LaunchAgents/com.apple.notificationcenterui.plist
$ uname -rsv
Darwin 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F34
$ sw_vers -productVersion
10.9.5
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.9.5 (13F34)
      Kernel Version: Darwin 13.4.0
      Boot Volume: [...]
      Boot Mode: Normal
      Computer Name: [...]
      User Name: [...]
      Secure Virtual Memory: [...]
      Time since boot: 10 minutes

```

**Comment by Tatsh** [comment]
Just FYI not everyone would probably be for set -e and similar things. http://mywiki.wooledge.org/BashFAQ/105

**Comment by lucafavatella** [comment]
I think the issue I saw was a combination of three factors:
1. Using `set -e`;
2. Not using superuser privileges (`sudo`);
3. Using a new version of `launchctl` - the one in OSX 10.10 - that changed semantics of exit status.

1 is debatable;
2 is not common yet (proposed in #579);
3 is unlucky.

So I am closing this PR - sorry for the noise.

@Tatsh Thanks for your explanations.

**Pull request closed without merging**
