### PR TITLE
Map Caps Lock to Left Control key

### PR DESCRIPTION
**Pull request by benjifs**

### CODE REVIEW

**Comment by chdiza** [comment]
From the cited Apple page:

> Key remappings are lost when the system is restarted

**Comment by chdiza** [comment]
There is already a persistent way to do this, by messing with `com.apple.keyboard.modifiermapping.1452-XXXX.plist`, where XXXX is a special code for a family of keyboard.  This is AFAIK the plist that gets written to if you use "SystemPreferences --> Keyboard --> Modifer Keys" to do the mapping.

I've been using this for years precisely to map my CapsLock to Control.

**Comment by benjifs** [comment]
My bad. From #310 I was not able to get it to work using that method on macOS. I was running this method and it worked fine for me but thats what I get for never restarting. I'll keep looking into a more permanent solution for this.

**Comment by chdiza** [comment]
I have a `MacBookPro9,2`, and the following has worked for years:
```
defaults write -g com.apple.keyboard.modifiermapping.1452-594-0 -array '<dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>'
```

I call this twice, the second time with a difference keyboard code to handle my USB keyboard and not just the built-in keyboard.

I got this from http://apple.stackexchange.com/questions/13598/updating-modifier-key-mappings-through-defaults-command-tool, where they also show how to find the particular keyboard code you need.

**Comment by bestswifter** [comment]
It seems this is impossible.

First, although you can vendor and product id and than edit the plist file, you can't determine the value. On old Mac, it's 0,2,10. However, in latest mac, this is a very large number looks like30064771296.

Second, I made an experiment only considering latest mac, though the plist file is the same as what it should looks like after changing modifier keys from GUI(System Preference), it still doesn' work.I diff two plist files and I am sure that they are the same.

**Comment by chdiza** [comment]
> It seems this is impossible.

It's not.  It's how for years now I map my Caps Lock to Control.

> you can't determine the value

Can't determine *what* value?  If you have vendor and product ID, then the key codes you need are in the table on the cited web page.  For each key you want to remap, you need a pair of those values.

**Comment by bestswifter** [comment]
Value means the value of key `HIDKeyboardModifierMappingDst` and `HIDKeyboardModifierMappingSrc`

I tried several times and am sure the plist file is modified correctly(by using diff), cou you please share your script?

**Comment by chdiza** [comment]
All I can tell you is that the `defaults` command in my earlier comment works on five different Macs of varying ages from 2008 to 2016, from Mavericks to Sierra and every OS in between, laptop and desktop, so long as I put the right digits at the end of `com.apple.keyboard.modifiermapping.`.

>  replace the plist file with that temp file

That will almost certainly not work for ANY preference setting, keyboard or otherwise, since preferences are cached.  You *must* use the `defaults` command.

**Comment by bestswifter** [comment]
As I said before, I tried to use `defaults write -g` but it faild, the plist file is the same as expected, but It's very strange that keys are not mapped.

I also tried your code in earlier comment and it didn't work either. Is that all what you use? Can you show me the full code?

**Comment by chdiza** [comment]
It *is* the full code.

**Comment by benjifs** [comment]
I found a way that is working on Sierra and High Sierra for me. The idea is the same that was discussed here but I wanted to automate the process so that I could just run the script once and it would fetch the vendor and product ids and map caps lock to the left control key for that device.

I didn't want to add the whole code block here so you can check the script here: [https://gist.github.com/benjifs/054e00deee252b5bb1b88e7afe590794](https://gist.github.com/benjifs/054e00deee252b5bb1b88e7afe590794)

Can someone confirm its also working for them before I submit a new PR?

With this method you can remap any key to any other key with the appropriate codes from [here](https://developer.apple.com/library/content/technotes/tn2450/_index.html)

**Comment by labianchin** [comment]
As an alternative you can use [Karabiner Elements](https://pqrs.org/osx/karabiner/) to map Caps Lock to Left Control.

**Comment by lucasff** [comment]
Why do you think this should be merged? like everyone wants this behaviour? I don't want that, for sure.

**Comment by martimlobao** [comment]
Reminds me of [this xkcd](https://xkcd.com/1172/).

**Comment by tamsky** [comment]
If you just want caps lock to go away, and become an additional Left_Control key, this is sufficient, but needs to be executed after each reboot.   See References for how to do that.
```
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E0}]'
```

References:
- https://www.nanoant.com/mac/macos-function-key-remapping-with-hidutil
- https://rakhesh.com/mac/using-hidutil-to-map-macos-keyboard-keys/
- Fancy script: https://mybyways.com/blog/script-to-re-map-macbook-pro-function-keys

**Pull request closed without merging**
