### PR TITLE
Updated show/hide to work with Yosemite

### PR DESCRIPTION
**Pull request by wamatt**
More info over here http://landonbaine.com/2014/09/how-to-os-x-yosemite-show-hidden-files-and-folders/

### CODE REVIEW

**Comment by alrra** [comment]
@wamatt

```bash
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
```

:point_up: Works for me, and I'm using OS X 10.10.2.

--

```bash
alias show="defaults write com.apple.finder AppleShowAllFiles -boolean true ; killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -boolean false ; killall Finder"
```

From `man defaults`:

```bash
 -bool[ean]  Allows the user to specify a boolean as the value for the given preference key. Value must be TRUE, FALSE, YES, or NO.
```

So, the change basically does the same thing as what is currently in this repository, the only difference being that `killall Finder` is executed no matter what the exit code is for the `defaults` command.

**Comment by mathiasbynens** [comment]
Closing as per https://github.com/mathiasbynens/dotfiles/pull/509#issuecomment-78007264.

**Comment by wamatt** [comment]
No problem. I would keep an eye on it though @alrra 

Sometimes it works for me, sometimes not (indeterministic)

I'm also on 10.10.2

**Comment by wamatt** [comment]
I realize it's anecdotal, but as you can see, some people are having issues.

http://coolestguidesontheplanet.com/show-hidden-library-and-user-library-folder-in-osx/

image

**Comment by mathiasbynens** [comment]
@wamatt Are you saying the modified version works all the time, while the current version is flaky?

**Comment by wamatt** [comment]
@mathiasbynens Only switched to the new syntax yesterday, and so far no problems.

I did a quick google search and then saw others had issues. Given you and @alrra having no issues, it's probably best to keep testing to see if it happens with the new syntax or merely coincidence.

One possibility could be that it's a race condition (or multiple factors of which syntax may not be the guilty suspect). The way users describe the issue, kind of hints at that.

https://discussions.apple.com/thread/6606145

**Comment by wamatt** [comment]
Another commenter thinks the unreliability is related to caching.

https://discussions.apple.com/message/24694675#24694675

<blockquote>
Mavericks uses a new caching system for plist files. I believe that when you use the Killall Finder command, the OS believes finder has crashed and replaces the finder plist file from the one it has in it's cache rather than reading the com.apple.finder.plist file. My tests showed that the defaults command (above) is writing the needed entry to the plist, but the Killall command is causing the plist file to revent back to the previous version (I assume from cache).
 
Initally I solved this by rebooting after the the defaults command (no killall). This seems to sync the cached version with the real file. Next I tried to see if there is a way to sync the cache without the reboot. The process that controls this is "cfprefsd". There are two instances of it running on Mavericks, one as user and one as root. If I used a Killall on this processes then it auto-restarts and seems to repopulate the cache from the file.
 
So... The following gets the job done most of the time:
 
defaults write com.apple.finder AppleShowAllFiles 1 && killall cfprefsd
 
I say most of the time simply because sometimes the the plist still manages to revert back. I'm pretty sure this could happen with the reboot method as well.
<blockquote>

**Pull request closed without merging**
