### PR TITLE
Extend Safari configuration to make it more secure

### PR DESCRIPTION
**Pull request by kdeldycke**
Ensure the basic Safari parameters are in good shape security-wise.

### CODE REVIEW

**Comment by kdeldycke** [comment]
This PR covers part of #306.

**Comment by kdeldycke** [comment]
Happy to contribute ! :)

**Comment by mathiasbynens** [comment]
Thanks! :)

**Comment by kdeldycke** [comment]
Thanks to you for being a considerate maintainer! :)

**Pull request closed without merging**
