### PR TITLE
Use function to update all

### PR DESCRIPTION
**Pull request by FradSer**
:-)

### CODE REVIEW

**Comment by thibmaek** [comment]
Just wondering? Why is this better by throwing it in a function rather than using the alias (I'm also using a function for this but just curious)

**Comment by FradSer** [comment]
```
alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup; brew cask update; brew cask cleanup; n io latest; n latest; npm update -g; pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U; sudo gem update'
```
or
``` shell
function update() {
	local softwareupdate="softwareupdate -i -a;"
	local brew="brew update; brew upgrade --all; brew cleanup;"
	local cask="brew cask update; brew cask cleanup;"
	local n="n io latest; n latest;"
	local npm="npm update -g;"
	local pip="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U;"
	local gem="gem update;"
	sudo sh -c "$softwareupdate"; sh -c "$brew$cask$n$npm$pip"; sudo sh -c "$gem"
}
```
I think function is better when you want to add more new tools.

**Comment by vinkla** [comment]
Even better would be to move it to the bin directory: https://github.com/vinkla/dotfiles/blob/master/bin/update

**Comment by d4rkr00t** [comment]
@vinkla :+1:

**Comment by thibmaek** [comment]
@FradSer Can see why that would make sense (I currently also do it like that)

@vinkla can see why a function would work but is there any upside to moving it to bin?

**Comment by vinkla** [comment]
@thibmaek IMO it looks cleaner and I find it easier to read. There are no advantages other than that.

**Comment by FradSer** [comment]
@vinkla @thibmaek 
``` shell
function update() {
	local softwareupdate="softwareupdate -i -a;"
	local brew="brew update; brew upgrade --all; brew cleanup;"
	local cask="brew cask update; brew cask cleanup;"
	local n="n io latest; n latest;"
	local npm="npm update -g;"
	local pip="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U;"
	local gem="gem update;"
	if [ "$1" == "--all" -o "$1" == "-a" -o "$1" == "" ]; then
		sudo -v;
		while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &;
		sudo sh -c "$softwareupdate";
		sh -c "$brew$cask$n$npm$pip";
		sudo sh -c "$gem";
	fi;
	if [ "$1" == "--softwareupdate" -o "$1" == "-s" ]; then
		sudo sh -c "$softwareupdate";
	fi;
	if [ "$1" == "--brew" -o "$1" == "-b" ]; then
		sh -c "$brew";
	fi;
	if [ "$1" == "--cask" -o "$1" == "-c" ]; then
		sh -c "$cask";
	fi;
	if [ "$1" == "--n" -o "$1" == "-n" ]; then
		sh -c "$n";
	fi;
	if [ "$1" == "--npm" -o "$1" == "-npm" ]; then
		sh -c "$npm";
	fi;
	if [ "$1" == "--pip" -o "$1" == "-p" ]; then
		sh -c "$pip";
	fi;
	if [ "$1" == "--gem" -o "$1" == "-g" ]; then
		sudo sh -c "$gem";
	fi;
}
```
This function can allow user control which ready to be updated.

**Comment by dserodio** [comment]
@thibmaek 
>  For almost every purpose, shell functions are preferred over aliases

Source: [Bash Reference Manual](https://www.gnu.org/software/bash/manual/html_node/Aliases.html)

**Pull request closed without merging**
