### PR TITLE
Change bootstrap to use symlink

### PR DESCRIPTION
**Pull request by githubutilities**
I think it is better to symlink the dotfiles instead of copying them so that we can change it in one place.

### CODE REVIEW

**Comment by d4rkr00t** [comment]
Hi, it's a good idea, thanks! I took it to my dotfiles.

**Comment by cemo** [comment]
+1

**Comment by williamboman** [comment]
This should not be the default behaviour, even though it may be preferable. I don't see why it couldn't be available through a flag though.

#301

**Comment by githubutilities** [comment]
I think symlink can save the works of changing it twice and I only navigate to my `dotfiles` folder to commit my changes rather than redoing my work. Why symlink should not be default behavior?

**Comment by githubutilities** [comment]
I think symlink can save the works of changing it twice so I only navigate to my `dotfiles` folder to commit my changes rather than redoing my works. Why symlink should not be default behavior?

**Comment by githubutilities** [comment]
@williamboman I think symlink can save the works of changing it twice so I only navigate to my dotfiles folder to commit my changes rather than redoing my works. Why symlink should not be default behavior?

**Comment by jrahmy** [comment]
@githubutilities Edit them in the dotfiles folder first, then run the install script.

**Comment by githubutilities** [comment]
@jrahmy Well, in that case, you have to run the `bootstrap.sh` script everytime you edit your dotfiles.

**Comment by hkdobrev** [comment]
:-1: 

I test things out in my dotfiles folder, I can pull from upstream and resolve merge conflicts. When I'm happy with the results I explicitly run the bootstrap script.

Also I can do some really quick changes in `~` and then choose to either discard them by running the bootstrap script or by copying them over to my dotfiles.

I can change branches in my dotfiles repo and fiddle with something without affecting my actual setup.

**Comment by mathiasbynens** [comment]
Thanks, but I prefer the current approach as well.

**Pull request closed without merging**
