### PR TITLE
Preserve Bash History in Multiple Terminal Windows

### PR DESCRIPTION
**Pull request by vinkla**
I consistently have more than one terminal open. Anywhere from two to ten, doing various bits and bobs. Now let's say I restart and open up another set of terminals. Some remember certain things, some forget.

I want a history that:
- Remembers everything from every terminal.
- Is instantly accessible from every terminal (eg if I ls in one, switch to another already-running terminal and then press up, ls shows up).
- Doesn't forget random things if there are spaces at the front of the command.

[Taken from this StackExchange question.](https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows)

### CODE REVIEW

**Comment by nilsi** [comment]
+1 this would be great!

**Comment by vinkla** [comment]
To be honest after using this for a while it can get a bit frustrating if you're used to the normal behavior.

**Comment by nvartolomei** [comment]
Having a large bash history file, what is overhead of rereading file after each command? I hate when I have to wait 1s or more until I can type next command just to execute these commands, git prompt and other things like that.

**Comment by vinkla** [comment]
I haven't had any performance issues since I exclude a lot of commands. Though, the history first updates when you have performed a new command between windows.

**Pull request closed without merging**
