### PR TITLE
Clarify source for bash-completion

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
I spent a solid 30 minutes debugging my git completion using these dotfiles. I had not yet run `brew.sh`. I had git completion installed, but it wasn't working because `.bash_profile` no longer separately sources `git-completion` in favor of the handy `bash-completion2`. I thought this note would be helpful to a common case where people have loaded the dotfiles but opted out of `brew.sh` and start poking around in `.bash_profile`, debugging their lack of git completion.

Thoughts?

### CODE REVIEW

**Comment by yangsu** [comment]
+1. It also requires for git to be installed via brew, so the required commands for git completions to work are as follows:

```
brew install git
brew tap homebrew/versions
brew install bash-completion2
```

**Comment by cemo** [comment]
There are a couple of commands which depends on https://github.com/mathiasbynens/dotfiles/blob/master/brew.sh. This part of the dotfiles is also depends `brew.sh`. It might be better to leave a note for in `README` file to indicate some of the features are depends on other packages which are installed by `brew.sh`.

**Comment by AndrewSouthpaw** [comment]
I'm happy to add that into the `README` if someone can sign off on it. :)

**Comment by AndrewSouthpaw** [comment]
Proposed some changes to `README`. :)

**Comment by mathiasbynens** [comment]
The problem with this change is that there are now 3 different places that need updating whenever the command to install Bash completion changes.

How about just making the `README.md` change, without explicitly repeating the installation commands there? I.e. just this part:

> Some of the functionality of these dotfiles leverages formulae installed by `brew.sh`. If you don't plan to run `brew.sh`, you should look carefully through the script and manually install any particularly important ones. A good example is bash/git completion: the dotfiles use a special version from Homebrew. To enable bash completion without running `brew.sh`:

**Comment by AndrewSouthpaw** [comment]
Simplified changes to just the README and condensed it to a single paragraph. I think it's still helpful to specify instructions on how to install this particular flavor of bash-completion, which is not immediately obvious. LMK if you think it's fine to have it as a single line, or I can nix it if you still feel strongly about it.

**Comment by mathiasbynens** [comment]
Thanks!

**Pull request closed without merging**
